name: build

on:
  push:
    branches: [rpg-hud-sync]
  workflow_dispatch:

jobs:
  ubuntu:
    name: Ubuntu ${{ matrix.arch }} ${{ matrix.build_type }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Create Build Environment
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get -y install aptitude
          sudo apt-get -y install gcc-multilib g++-multilib ninja-build
          sudo apt-get -y install --allow-downgrades libpcre2-8-0:i386 libjpeg-dev:i386 libpng-dev:i386 libcurl4-openssl-dev:i386
          sudo aptitude -y install libglib2.0-dev:i386 libsdl2-dev:i386
          cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: |
          OPTIONS="-DUseInternalLibs=OFF -DBuildPortableVersion=OFF -DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/install"
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} $OPTIONS -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchains/linux-i686.cmake

      - name: Build Dedicated Server Only
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: cmake --build . --target openjkded.i386 --config Release

      - name: Prepare Artifact
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: |
          mkdir -p ${{ runner.workspace }}/artifact
          cp openjkded.i386 ${{ runner.workspace }}/artifact/openjkded.i386

      - uses: actions/upload-artifact@v4
        with:
          name: openjkded-linux-i386
          path: ${{ runner.workspace }}/artifact/openjkded.i386
          if-no-files-found: error
